config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'invoices#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:amount, :company, :contragent, :currency, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>
      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="card">
  <div class=" field">
    <%= form.label :amount %>
    <%= form.text_field :amount, {:class => 'form-control'} %> 
  </div>


  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, {:class => 'form-control'} %>
  </div>

  <div class="field">
    <%= form.label :contragent %>
    <%= form.text_field :contragent, {:class => 'form-control'} %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency, {:class => 'form-control'} %>
  </div>
</div>
  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, {:class => 'form-control dropdown-menu'} %>
  </div>

  <div class="field">
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </div>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
<div class="card">

      <div class="card-heading">
    
      <h1 class="card-title text-center"> Invoices</h1>
      </div>
      
      <div class="card-body">
        <table class=" table table-hover table-bordered">
          <thead>
            <tr>
              
              <th>Company</th>
              <th>Contragent</th>
              <th>Amount</th>
              <th>Date</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @invoices.each do |invoice| %>
              <tr>
              
                <td><%= invoice.company %></td>
                <td><%= invoice.contragent %></td>
                <td><%= invoice.amount %> <%= invoice.currency %></td>
                <td><%= invoice.date %></td>
                <td><%= link_to 'Show', invoice %></td>
                <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
                <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
              <div class="card-footer">
                  <%= link_to 'New Invoice', new_invoice_path, class: "btn btn-primary" %>
                </div>
              </div>
          </div>
        </div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="card">

      <div class="card-heading">
    
      <h1 class="card-title"> Invoices</h1>
      </div>
      
      <div class="card-body">

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Contragent:</strong>
  <%= @invoice.contragent %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invoice.amount %><%= @invoice.currency %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>
      </div>
      <div class="panel-footer">
      <div class="btn-group">
      <%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-danger" %> |
<%= link_to 'Back', invoices_path, class: "btn btn-warninig"  %>

    </div>      
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoices</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  </head>
  <body>
  
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <a class="navbar-brand" href="#">Invoice</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li><%= link_to "Invoices", invoices_path %></li>
            </ul>
        

          </div>
        </nav>
        <div class="container">
          <%= yield %>
        </main>
  </body>
</html>